Add OpenStack questions

diff --git a/scripts/install_bootstrap b/scripts/install_bootstrap
--- a/scripts/install_bootstrap
+++ b/scripts/install_bootstrap
@@ -108,8 +108,9 @@ while [[ "${run_pancancer_launcher^^}" != 'Y' &&  "${run_pancancer_launcher^^}" 
 		done
 
 		if [ $user_cloud_env == 'AWS' ] ; then
-
-	    	# load AWS config
+			############################
+	    	# AWS questions
+			############################
 	    	if [ -f ~/.aws/config ] ; then
 	    		AWS_KEY=$(grep aws_access_key_id ~/.aws/config | sed 's/\(.*=\)//g')
 	    		AWS_SECRET_KEY=$(grep aws_secret_access_key ~/.aws/config | sed 's/\(.*=\)//g')
@@ -161,6 +162,9 @@ region=us-east-1
 output=json
 AWS_CONFIG
 		
+		############################
+		# AZURE QUESTIONS
+		############################
 		elif [ $user_cloud_env == 'Azure' ] ; then
 	    	user_azure_subscription_id=''
 			while [[ -z "${user_azure_subscription_id// /}" ]] ; do
@@ -203,7 +207,7 @@ AWS_CONFIG
 				if [ ! -z $AZURE_AD_USER ] ; then
 					read -ep $'What is your Azure Active Directory user name? Previous value: \n' -i $AZURE_AD_USER user_azure_AD_user
 				else
-					read -ep $'What is your Azure storage account key?\n' user_azure_AD_user
+					read -ep $'What is your Azure Active directory user name?\n' user_azure_AD_user
 				fi
 				if [[ -z "${user_azure_AD_user// /}" ]] ; then
 					echo 'Azure Active Directory username cannot be blank.'
@@ -213,19 +217,103 @@ AWS_CONFIG
 			user_azure_AD_passwd=''
 			while [[ -z "${user_azure_AD_passwd// /}" ]] ; do
 				if [ ! -z $AZURE_AD_PASSWD ] ; then
-					read -ep $'What is your Azure Active Directory user name? Previous value: \n' -i $AZURE_AD_PASSWD user_azure_AD_passwd
+					read -ep $'What is your Azure Active Directory password? Previous value: \n' -i $AZURE_AD_PASSWD user_azure_AD_passwd
 				else
-					read -ep $'What is your Azure storage account key?\n' user_azure_AD_passwd
+					read -ep $'What is your Azure Active Directory password?\n' user_azure_AD_passwd
 				fi
 				if [[ -z "${user_azure_AD_passwd// /}" ]] ; then
 					echo 'Azure Active Directory username cannot be blank.'
 				fi
 			done
 
-		elif [ $user_cloud_env == 'OpenStack' ] ; then
-			#TODO: finish
-		fi
+			user_azure_AD_tentant=''
+			while [[ -z "${user_azure_AD_tentant// /}" ]] ; do
+				if [ ! -z $AZURE_AD_TENTANT ] ; then
+					read -ep $'What is your Azure Active Directory Tentant ID? Previous value: \n' -i $AZURE_AD_TENTANT user_azure_AD_tenant
+				else
+					read -ep $'What is your Azure Active Directory Tentant ID?\n' user_azure_AD_tenant
+				fi
+				if [[ -z "${user_azure_AD_tentant// /}" ]] ; then
+					echo 'Azure Active Directory Tentant ID cannot be blank.'
+				fi
+			done
 
+			user_azure_AD_client=''
+			while [[ -z "${user_azure_AD_client// /}" ]] ; do
+				if [ ! -z $AZURE_AD_CLIENT ] ; then
+					read -ep $'What is your Azure Active Directory Client ID? Previous value: \n' -i $AZURE_AD_CLIENT user_azure_AD_client
+				else
+					read -ep $'What is your Azure Active Directory Client ID?\n' user_azure_AD_client
+				fi
+				if [[ -z "${user_azure_AD_client// /}" ]] ; then
+					echo 'Azure Active Directory Client ID cannot be blank.'
+				fi
+			done
+
+		elif [ $user_cloud_env == 'OpenStack' ] ; then
+			############################
+	    	# OpenStack questions
+			############################
+			
+			user_os_username=''
+			while [[ -z "${user_os_username// /}" ]] ; do
+				if [ ! -z $OS_USERNAME ] ; then
+					read -ep $'What is your OpenStack username (<tenant>:<username>)? Previous value: \n' -i $OS_USERNAME user_os_username
+				else
+					read -ep $'What is your OpenStack username (<tenant>:<username>)?\n' user_os_username
+				fi
+				if [[ -z "${user_os_username// /}" ]] ; then
+					echo 'OpenStack username cannot be blank.'
+				fi
+			done
+
+			user_os_password=''
+			while [[ -z "${user_os_password// /}" ]] ; do
+				if [ ! -z $OS_PASSWORD ] ; then
+					read -ep $'What is your OpenStack password? Previous value: \n' -i $OS_PASSWORD user_os_password
+				else
+					read -ep $'What is your OpenStack password?\n' user_os_password
+				fi
+				if [[ -z "${user_os_password// /}" ]] ; then
+					echo 'OpenStack password cannot be blank.'
+				fi
+			done
+			
+			user_os_endpoint=''
+			while [[ -z "${user_os_endpoint// /}" ]] ; do
+				if [ ! -z $OS_ENDPOINT ] ; then
+					read -ep $'What is your OpenStack API endpoint? Previous value: \n' -i $OS_ENDPOINT user_os_endpoint
+				else
+					read -ep $'What is your OpenStack API endpoint?\n' user_os_endpoint
+				fi
+				if [[ -z "${user_os_endpoint// /}" ]] ; then
+					echo 'OpenStack endpoint cannot be blank.'
+				fi
+			done
+
+			
+			user_os_region=''
+			while [[ -z "${user_os_region// /}" ]] ; do
+				if [ ! -z $OS_REGION ] ; then
+					read -ep $'What is your OpenStack region? Previous value: \n' -i $OS_REGION user_os_region
+				else
+					read -ep $'What is your OpenStack region?\n' user_os_region
+				fi
+				if [[ -z "${user_os_region// /}" ]] ; then
+					echo 'OpenStack region cannot be blank.'
+				fi
+			done
+			
+			user_os_zone=''
+			if [ ! -z $OS_ZONE ] ; then
+				read -ep $'What is your OpenStack zone? Previous value: \n' -i $OS_REGION user_os_zone
+			else
+				read -ep $'What is your OpenStack zone?\n' user_os_zone
+			fi
+		else
+			echo "Unrecognized cloud environment: $user_cloud_env, exiting..."
+			exit 1
+		fi
 		# echo "What version of the pancancer_launcher do you wish to run (default will be \"latest\")?"
 		# read user_pancancer_version
 		# They already pulled "latest", earlier in this script, so just stick with that. Future versions could ask this question, if necessary...
@@ -281,9 +369,25 @@ PEM_PATH=${user_pem_path}
 KEY_NAME=${user_key_name}
 FLEET_NAME=${user_fleet_name}
 FLEET_SIZE=${user_fleet_size}
-SECURITY_GROUP=${user_sec_grp}
 WORKFLOW_LISTING_URL=${workflow_listing_url}
 CLOUD_ENV=${user_cloud_env}
+
+SECURITY_GROUP=${user_sec_grp}
+
+AZURE_SUBSCRIPTION=${user_azure_subscription_id}
+AZURE_STORAGE_ACCOUNT=${user_azure_storage_account_name}
+AZURE_STORAGE_ACCOUNT_KEY=${user_azure_storage_account_key}
+AZURE_AD_USER=${user_azure_AD_user}
+AZURE_AD_PASSWD=${user_azure_AD_passwd}
+AZURE_AD_TENTANT=${user_azure_AD_tentant}
+AZURE_AD_CLIENT=${user_azure_AD_client}
+
+OS_USERNAME=${user_os_username}
+OS_PASSWORD=${user_os_password}
+OS_ENDPOINT=${user_os_endpoint}
+OS_REGION=${user_os_region}
+OS_ZONE=${user_os_zone}
+
 CONFIG
     [[ -d "/home/$USER/pancancer_launcher_config" ]] || mkdir "/home/$USER/pancancer_launcher_config"
     cp ~/.pancancer/pancancer.config /home/$USER/pancancer_launcher_config/pancancer.config
