Add error handling for other installs.

diff --git a/scripts/install_bootstrap b/scripts/install_bootstrap
--- a/scripts/install_bootstrap
+++ b/scripts/install_bootstrap
@@ -41,8 +41,31 @@ while [[ "${install_pancancer_launcher^^}" != 'Y' &&  "${install_pancancer_launc
 		if [ "$user_install_docker" = 'Y' ] ; then
 			echo "Installing docker..."
 			sleep 2
-			sudo apt-get install wget curl --yes &> install_wget_curl.log && curl -sSL https://get.docker.com/ | sh &> install_docker.log
+			
+			set +e
+			sudo apt-get install wget curl --yes &> install_wget_curl.log
+			install_wget_result=$?
+			set -e
+			
+			if [ $install_wget_result -ne  0 ] ; then
+				echo "It looks like there may have been a problem installing or updated wget and curl:" 
+				cat install_wget_curl.log
+				exit 1
+			fi
+			
+			set +e
+			curl -sSL https://get.docker.com/ | sh &> install_docker.log
+			install_docker_result=$?
+			set -e
+			
+			if [ $install_docker_result -ne  0 ] ; then
+				echo "It looks like there may have been a problem installing docker:" 
+				cat install_wget_curl.log
+				exit 1
+			fi
+			
 			echo "Done installing docker!"
+			DOCKER_PATH="$(which docker)"
 		else
 			echo "Skipping docker installation..."
 		fi
@@ -57,7 +80,7 @@ while [[ "${install_pancancer_launcher^^}" != 'Y' &&  "${install_pancancer_launc
 			pull_result=$?
 			set -e
 			if [ $pull_result -ne  0 ] ; then
-				echo "It looks like there might have been an error when pulling the docker image. The pancancer_launcher cannot be run until this is resolved. " 
+				echo "It looks like there might have been an error when pulling the docker image. The pancancer_launcher cannot be run until this is resolved. Error is:" 
 				cat pull_image.log
 				exit 1
 			fi
