Check that docker is installed before pulling image. Conflicts: 	scripts/install_bootstrap

diff --git a/scripts/install_bootstrap b/scripts/install_bootstrap
--- a/scripts/install_bootstrap
+++ b/scripts/install_bootstrap
@@ -48,15 +48,28 @@ while [[ "${install_pancancer_launcher^^}" != 'Y' &&  "${install_pancancer_launc
 			sudo apt-get install wget curl
 			echo "Installing docker..."
 			sleep 2
-			sudo apt-get install wget curl --yes && curl -sSL https://get.docker.com/ | sh &> install_docker.log
+			sudo apt-get install wget curl --yes &> install_wget_curl.log && curl -sSL https://get.docker.com/ | sh &> install_docker.log
 			echo "Done installing docker!"
-
 		else
 			echo "Skipping docker installation..."
 		fi
-		echo "Pulling pancancer_launcher image..."
-		sudo docker pull pancancer/pancancer_launcher:"${user_pancancer_version}" &> pull_image.log
-		echo "Done pulling pancancer_launcher!"
+		
+		if [ -z "$DOCKER_PATH" ] ; then
+			echo "You need to install docker before pulling docker images. Please ensure that docker is properly installed and then re-run this script with the command \"bash install_bootstrap\""
+			exit 1
+		else
+			echo "Pulling pancancer_launcher image..."
+			set +e
+			sudo docker pull pancancer/pancancer_launcher:"${user_pancancer_version}" &> pull_image.log
+			pull_result=$?
+			set -e
+			if [ $pull_result -ne  0 ] ; then
+				echo "It looks like there might have been an error when pulling the docker image. The pancancer_launcher cannot be run until this is resolved. " 
+				cat pull_image.log
+				exit 1
+			fi
+			echo "Done pulling pancancer_launcher!"
+		fi
 	elif [ "${install_pancancer_launcher^^}" = 'N' ] ; then
 		echo "You are exiting the installer now, but you can always run it again when you are ready."
 		exit 0
@@ -164,7 +177,7 @@ AWS_CONFIG
 		# echo "What version of the pancancer_launcher do you wish to run (default will be \"latest\")?"
 		# read user_pancancer_version
 		# They already pulled "latest", earlier in this script, so just stick with that. Future versions could ask this question, if necessary...
-		#user_pancancer_version="L4A_1.0.0-rc.0"
+		#user_pancancer_version="latest"
 
 		user_fleet_name=''
 		if [ ! -z $FLEET_NAME ] ; then
